# Generated by Django 5.0.2 on 2024-02-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_details_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='age',
        ),
    ]
