# Generated by Django 5.0.2 on 2024-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_details_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadidate_name', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('candidate_id', models.CharField(max_length=20)),
            ],
        ),
    ]
